travis:
  secure:
    BINSTAR_TOKEN: lw91sSUD19GqnCGDCpJQgxeqKA7ljJUeF+A13VuYUXV4CyoqsifkqDkTAr7E5pq//fs7rQ5dFMLnwa9K2uTefCqFDViZm3fEFFJxsJXscLRIMcFu8pP9pPKxR0RwGNrlyAxuPlB/Go8JK2EE2CU+JqVojW7Pb8UCjxxSto4YdAmKJ8Lsp3Zmi9vBs+WzDO9GsxIdRKEL0rFl3dR6/m3DqDQmpCagvICExNIjPsNFBF6ZRrw6zMZ6GBjUkyg7ZQ4qWgTKBhLdB9oxK9LLLdux1B6/yO4P4RdzdfvnACLwH3WhBHZAQ+0AbeTvr9qo2qKgvgVlJrFbZT8gk7L1aQ8/+QW8QqP6lqF0DSUGWgRBapZlN4yJMC4DoQZH0zLBUAYyHv2XZDG1BlOFpBVA/80MsIOURuAhC1U5tTiS/5jnpdEeeYwVZ/Ulqhhhth8IkrHA6t3Gj/zxMuGo4Q0jPR3OZgTcM6iljL3mZRTc399GYL+eeu/AIcEy/pq2xLnPkOreI0bOa80aG/z89d9rt7kIeG9wlwAJZ0ahMHWPVxH4qVx2+Tz84j8pVgd9C1Tn78h+1vilwN3sNYHmnIE1oLYm5mI0rArAoRJx0wMpbN9tv+Xi2Tka8HZJk0p7wSFY0qhXSAoc9d9mZX6ePphYz/Grs53sJOVbK31YRGJO2XVwDJ0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
